### ISSUE TITLE
slopedplanesmacro

### ISSUE THREAD

**Issue by ghost** [furti/FreeCAD-ArchTextures#23]
You can find the sloped planes repository at
https://gitlab.com/damianCaceres/slopedplanes
only for gitlab signed users

**Comment by furti** [comment]
I don't think this is the right place for disucssions about the sloped planes macro. Maybe you can explain the reasons why you deleted your complete GitHub account and the sloped planes macro in this Forum thread: https://forum.freecadweb.org/viewtopic.php?f=24&t=25337&start=80

I don't have an gitlab account. So I can't check the repository now. But when the gitlab repository is only available when someone logs in, how can FreeCAD Users download your workbench to use it with FreeCAD?

As suggested by me in this forum post https://forum.freecadweb.org/viewtopic.php?f=24&t=25337&start=90#p278604 I will update luzpaz repo with the version I have locally installed. So FreeCAD Users can continue to use the macro until we know what you have planned for the future :)

Hope this is OK for you.

**Comment by ghost** [comment]
No. I can't explain it in the freecad forum because my freecad account has been cancelled. I can't participate more in the freecad forum. Try to find me in the freecad user list.
I've migrated to gitlab. There you can find the last modifications. No more code in github.
Bye.

**Comment by ghost** [comment]
Freecad account closed by Administrators
